### ISSUE TITLE
yet another linux make problem

### ISSUE THREAD

**Issue by Ph4n70mh4x0r** [silicontrip/SkyReader#27]
when i do amke it gives me this gcc -c -o hid.o hid.c
hid.c:25:10: fatal error: IOKit/hid/IOHIDManager.h: No such file or directory
 #include <IOKit/hid/IOHIDManager.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:19: recipe for target 'hid.o' failed
make: *** [hid.o] Error 1

**Comment by Ph4n70mh4x0r** [comment]
i am an idiot

**Comment by Ph4n70mh4x0r** [comment]
this is for mac and pc

**Comment by silicontrip** [comment]
err yeah because my question to your original question would be, what version of OSX are you getting this error on?  And if you say you're not building this on OSX, I'll say you're using the wrong version of hid.c, I'm pretty sure there is a linux hid.c hiding in one of the forks of this project.

Good luck.

**Comment by Ph4n70mh4x0r** [comment]
yeah
